### ISSUE TITLE
Problemer med bruk av klienten på java 1.6.x 

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#13]
Har et problem med å bruke meldingsformidlerklienten på java 1.6.X. Det fungerer utmerket med java 1.7. Av diverse årsaker er vi avhengig av å kunne benytte 1.6.x.

Får denne feilmeldingen ved bruk av 1.6.X
 
no.difi.sdp.client.domain.exceptions.KonfigurasjonException: Kunne ikke initialisere xml-signering
                at no.difi.sdp.client.asice.signature.CreateSignature.<init>(CreateSignature.java:97)
                at no.difi.sdp.client.asice.CreateASiCE.<init>(CreateASiCE.java:49)
                at no.difi.sdp.client.internal.CreateDokumentpakke.<init>(CreateDokumentpakke.java:35)
                at no.difi.sdp.client.internal.EbmsForsendelseBuilder.<init>(EbmsForsendelseBuilder.java:38)
                at no.difi.sdp.client.SikkerDigitalPostKlient.<init>(SikkerDigitalPostKlient.java:50)
                at no.si.sdp.MeldingsformidlerClient.<init>(MeldingsformidlerClient.java:31)
                at no.si.sdp.MeldingsformidlerClient.main(MeldingsformidlerClient.java:39)
Caused by: java.security.NoSuchAlgorithmException: http://www.w3.org/2006/12/xml-c14n11 algorithm and DOM mechanism not available
                at javax.xml.crypto.dsig.TransformService.getInstance(TransformService.java:153)
                at org.jcp.xml.dsig.internal.dom.DOMXMLSignatureFactory.newCanonicalizationMethod(DOMXMLSignatureFactory.java:253)
                at no.difi.sdp.client.asice.signature.CreateSignature.<init>(CreateSignature.java:93)
                ... 6 more
Exception in thread "main" java.lang.RuntimeException: Kunne ikke initiere keystore! Kunne ikke initialisere xml-signering
                at no.si.sdp.MeldingsformidlerClient.<init>(MeldingsformidlerClient.java:34)
                at no.si.sdp.MeldingsformidlerClient.main(MeldingsformidlerClient.java:39)

**Comment by asjafjell** [comment]
Dette kortet har ingen utestående oppgaver. Lukker saken.
