### ISSUE TITLE
Feil under oppretting av SikkerDigitalPostKlient

### ISSUE THREAD

**Issue by mhoel** [difi/sikker-digital-post-klient-java#52]
Oppretter en SikkerDigitalPostKlient og får feil i biblioteket under oppretting av JAXB marshaller. Legger ved stacktrace.

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at no.digipost.api.xml.Marshalling.getMarshallerSingleton(Marshalling.java:67)
	at no.digipost.api.MessageSender$Builder.getDefaultMarshaller(MessageSender.java:338)
	at no.digipost.api.MessageSender$Builder.build(MessageSender.java:240)
	at no.difi.sdp.client2.internal.DigipostMessageSenderFacade.<init>(DigipostMessageSenderFacade.java:68)
	at no.difi.sdp.client2.SikkerDigitalPostKlient.<init>(SikkerDigitalPostKlient.java:38)
	at no.difi.meldingsutveksling.ptp.MeldingsformidlerClient.sendMelding(MeldingsformidlerClient.java:49)
	at no.difi.meldingsutveksling.ptp.MeldingsformidlerClientMain.main(MeldingsformidlerClientMain.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
...
Two classes have the same XML type name "{http://www.w3.org/2000/09/xmldsig#}SPKIDataType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at org.w3.xmldsig.SPKIData
		at protected java.util.List org.w3.xmldsig.KeyInfo.content
		at org.w3.xmldsig.KeyInfo
		at protected org.w3.xmldsig.KeyInfo org.w3.xmldsig.Signature.keyInfo
		at org.w3.xmldsig.Signature
		at public org.w3.xmldsig.Signature org.w3.xmldsig.ObjectFactory.createSignature()
		at org.w3.xmldsig.ObjectFactory
		at protected java.util.List org.w3.xmldsig.CanonicalizationMethod.content
		at org.w3.xmldsig.CanonicalizationMethod
	this problem is related to the following location:
		at org.w3._2000._09.xmldsig_.SPKIDataType
		at public org.w3._2000._09.xmldsig_.SPKIDataType org.w3._2000._09.xmldsig_.ObjectFactory.createSPKIDataType()
		at org.w3._2000._09.xmldsig_.ObjectFactory
		at protected java.util.List org.w3._2000._09.xmldsig_.CanonicalizationMethodType.content
		at org.w3._2000._09.xmldsig_.CanonicalizationMethodType
		at protected org.w3._2000._09.xmldsig_.CanonicalizationMethodType org.w3._2000._09.xmldsig_.SignedInfoType.canonicalizationMethod
		at org.w3._2000._09.xmldsig_.SignedInfoType
		at protected org.w3._2000._09.xmldsig_.SignedInfoType org.w3._2000._09.xmldsig_.SignatureType.signedInfo
		at org.w3._2000._09.xmldsig_.SignatureType
		at protected org.w3._2000._09.xmldsig_.SignatureType org.etsi.uri._01903.v1_3.CounterSignatureType.signature
		at org.etsi.uri._01903.v1_3.CounterSignatureType
The element name {http://www.w3.org/2000/09/xmldsig#}KeyName has more than one mapping.
	this problem is related to the following location:
		at public javax.xml.bind.JAXBElement org.w3._2000._09.xmldsig_.ObjectFactory.createKeyName(java.lang.String)
		at org.w3._2000._09.xmldsig_.ObjectFactory
		at protected java.util.List org.w3._2000._09.xmldsig_.CanonicalizationMethodType.content
		at org.w3._2000._09.xmldsig_.CanonicalizationMethodType
		at protected org.w3._2000._09.xmldsig_.CanonicalizationMethodType org.w3._2000._09.xmldsig_.SignedInfoType.canonicalizationMethod
		at org.w3._2000._09.xmldsig_.SignedInfoType
		at protected org.w3._2000._09.xmldsig_.SignedInfoType org.w3._2000._09.xmldsig_.SignatureType.signedInfo
		at org.w3._2000._09.xmldsig_.SignatureType
		at protected org.w3._2000._09.xmldsig_.SignatureType org.etsi.uri._01903.v1_3.CounterSignatureType.signature
		at org.etsi.uri._01903.v1_3.CounterSignatureType
	this problem is related to the following location:
		at public javax.xml.bind.JAXBElement org.w3.xmldsig.ObjectFactory.createKeyName(java.lang.String)
		at org.w3.xmldsig.ObjectFactory
		at protected java.util.List org.w3.xmldsig.CanonicalizationMethod.content
		at org.w3.xmldsig.CanonicalizationMethod
The element name {http://www.w3.org/2000/09/xmldsig#}MgmtData has more than one mapping.
	this problem is related to the following location:
		at public javax.xml.bind.JAXBElement org.w3._2000._09.xmldsig_.ObjectFactory.createMgmtData(java.lang.String)
		at org.w3._2000._09.xmldsig_.ObjectFactory
		at protected java.util.List org.w3._2000._09.xmldsig_.CanonicalizationMethodType.content
		at org.w3._2000._09.xmldsig_.CanonicalizationMethodType
		at protected org.w3._2000._09.xmldsig_.CanonicalizationMethodType org.w3._2000._09.xmldsig_.SignedInfoType.canonicalizationMethod
		at org.w3._2000._09.xmldsig_.SignedInfoType
		at protected org.w3._2000._09.xmldsig_.SignedInfoType org.w3._2000._09.xmldsig_.SignatureType.signedInfo
		at org.w3._2000._09.xmldsig_.SignatureType
		at protected org.w3._2000._09.xmldsig_.SignatureType org.etsi.uri._01903.v1_3.CounterSignatureType.signature
		at org.etsi.uri._01903.v1_3.CounterSignatureType
	this problem is related to the following location:
		at public javax.xml.bind.JAXBElement org.w3.xmldsig.ObjectFactory.createMgmtData(java.lang.String)
		at org.w3.xmldsig.ObjectFactory
		at protected java.util.List org.w3.xmldsig.CanonicalizationMethod.content
		at org.w3.xmldsig.CanonicalizationMethod
Two classes have the same XML type name "{http://uri.etsi.org/01903/v1.3.2#}SPUserNoticeType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at org.etsi.uri._01903.v1_3.SPUserNotice
		at public org.etsi.uri._01903.v1_3.SPUserNotice org.etsi.uri._01903.v1_3.ObjectFactory.createSPUserNotice()
		at org.etsi.uri._01903.v1_3.ObjectFactory
		at protected java.util.List org.etsi.uri._01903.v1_3.Any.content
		at org.etsi.uri._01903.v1_3.Any
	this problem is related to the following location:
		at org.etsi.uri._01903.v1_3.SPUserNoticeType
There's no ObjectFactory with an @XmlElementDecl for the element {http://uri.etsi.org/01903/v1.3.2#}CounterSignature.
	this problem is related to the following location:
		at protected java.util.List org.etsi.uri._01903.v1_3.UnsignedSignaturePropertiesType.counterSignatureOrSignatureTimeStampOrCompleteCertificateRefs
		at org.etsi.uri._01903.v1_3.UnsignedSignaturePropertiesType
		at protected org.etsi.uri._01903.v1_3.UnsignedSignaturePropertiesType org.etsi.uri._01903.v1_3.UnsignedPropertiesType.unsignedSignatureProperties
		at org.etsi.uri._01903.v1_3.UnsignedPropertiesType
		at protected org.etsi.uri._01903.v1_3.UnsignedPropertiesType org.etsi.uri._01903.v1_3.QualifyingPropertiesType.unsignedProperties
		at org.etsi.uri._01903.v1_3.QualifyingPropertiesType

	at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(IllegalAnnotationsException.java:91)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:445)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:277)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:124)
	at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1123)
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(ContextFactory.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:247)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:234)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:462)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:641)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:584)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.createJaxbContextFromPackages(Jaxb2Marshaller.java:522)
	at org.springframework.oxm.jaxb.Jaxb2Marshaller.getJaxbContext(Jaxb2Marshaller.java:459)
	... 14 more`

**Comment by mhoel** [comment]
Beklager den lange stacktracen.

Ser ut som konflikten er at JAXB marshaller finner duplikater på classpath. Det er to avhengigheter som inkluderer JAXB genererte utgaver av elementer som "{http://uri.etsi.org/01903/v1.3.2#}ObjectIdentifierType". Objektene har samme pakkenavn og klassenavn og ligger vel på samme classpath i modulen jeg prøver å kjøre.

Avhengighetene det gjelder er no.digipost:sdp-xsd:1.1.19 og no.difi.commons:commons-asic:0.9.2

**Comment by runeflobakk** [comment]
Det er tydelig at commons-asic ikke spiller så veldig på lag med sdp-xsd ja.
De genererte JAXB-klassene for `ts_102918v010201.xsd` i hhv. sdp-xsd og commons-asic er generert i _samme pakke_, men selve kodegenereringen er konfigurert litt ulikt. Dette medfører for eksempel at i sdp-xsd har XML-typen `ObjectIdentifierType` fått klassen `org.etsi.uri._01903.v1_3.ObjectIdentifier`, mens i commons-asic heter den `org.etsi.uri._01903.v1_3.ObjectIdentifierType`. Dette fører igjen til en salig blanding av klasser som lastes både fra sdp-xsd og commons-asic.

Jeg vet ikke sånn umiddelbart om noen superenkelt fiks på dette. Kanskje burde de genererte klassene bygges til en pakke som åpenbart er internt for de respektive artifaktene. Dette kan vel konfigureres med JAXB-bindings:
```xml
<bindings schemaLocation="ts_102918v010201.xsd">
    <schemaBindings>
        <package name="no.difi.commons.org.etsi.uri"/>
    </schemaBindings>
</bindings>
```

**Comment by aberner** [comment]
Dette ligner vel veldig på tidligere konflikt mellom dette biblioteket og oppslagstjenesten. #23

Så håper det er en enkel fiks på dette.

**Comment by mhoel** [comment]
Takk for svar! Jeg fant ut at parent pom-en hadde en avhengighet til commons-asic (og det skal den jo ikke ha).

Men det er litt u-kult at disse avhengighetene ikke kan være på classpath sammen :)

En kjapp fiks hadde vært som du nevner @runeflobakk nevner å legge til en jaxb binding sånn at det ikke blir noe navnekollisjon. Alternativt kunne man skilt ut generering i en egen avhengighet som deles av begge prosjektene (som man får mulighet til å ekskludere)

**Comment by mhoel** [comment]
Det er en setting til jaxb maven plugins som quick-fikser problemet ganske enkelt. Under configuration kan man legge til et xml element som angir pakkenavn alt skal genereres under. (Ikke alltid det blir så vakkert hvis det er flere skjema).

<packageName>no.difi.prosjektnavn[..].etsi</packageName> under <configuration> for jaxb-plugin

I maven-jaxb2-plugin er det <generatePackage>no.difi.prosjekt...etsi</generatePackage>
Ellers for jaxws-maven-plugin<packageName></packageName>

**Comment by asjafjell** [comment]
Siden løsningen ble postet av @mhoel og ingen aktivitet har vært her på 1 måned så regner jeg med dette er fikset i det andre biblioteket.

**Comment by mhoel** [comment]
@asjafjell vi fikset det ved å opprette en modifisert lokal versjon av det andre biblioteket hvor jeg la til jaxb bindings for de xsd-ene det måtte gjelde. Jeg er litt usikker på veien vår videre med denne. Nå er ikke dette direkte feil i dette prosjektet, men heller i en av avhengighetene no.digipost:sdp-xsd.

    
    <bindings scd="x-schema::e" xmlns:e="http://uri.etsi.org/01903/v1.3.2#">
        <schemaBindings>
            <package name="no.difi.xsd.org.etsi._01903.v1_3"/>
        </schemaBindings>
    </bindings>

    
    <bindings scd="x-schema::x" xmlns:x="http://www.w3.org/2000/09/xmldsig#">
        <schemaBindings>
            <package name="no.difi.xsd.org.w3._2000._09.xmldsig"/>
        </schemaBindings>
    </bindings>
